version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - ./static:/app/static
      - media_volume:/app/media
      - ./courseproject/static:/app/courseproject/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=courseproject.settings

volumes:
  static_volume:
  media_volume: