# Generated by Django 3.1.1 on 2025-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instructor_bio',
            field=models.TextField(blank=True, null=True, verbose_name='Instructor Bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='Is Instructor?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
    ]
