# Generated by Django 3.1.1 on 2025-02-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250211_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instructor_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_instructor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website_url',
        ),
    ]
