# Generated by Django 3.1.1 on 2025-02-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_courserating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
